services:
  - type: web
    name: Text Leech Bot
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/tejp1234/text-leech-bot
    branch: main
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        value: <YOUR_BOT_TOKEN>
      - key: API_ID
        value: <YOUR_API_ID>
      - key: API_HASH
        value: <YOUR_API_HASH>
      - key: WEBHOOK
        value: 'false'
      - key: PORT
        value: '8000'
