services:
  - type: web
    name: Text Leech Bot
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/tejp1234/text-leech-bot-for-render
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        value: 7281646935:AAGyP75c8F3lnwV51cuDGqign9jJHFxqKDc
      - key: API_ID
        value: 27307674
      - key: API_HASH
        value: fa234730dc7fbe45cab70e9f242f1a94
      - key: WEBHOOK
        value: false
      - key: PORT
        value: 8000
